### PR TITLE
Proposed teeth-latest

### PR DESCRIPTION
**Pull request by jayofdoom**

### CODE REVIEW

**Comment by jimrollenhagen** [comment]
+1 assuming tests pass.

**Comment by jayofdoom** [comment]
Travis is slow; this passes locally.

```
vagrant@vagrant-ubuntu-trusty-64:/data/Users/jay/dev/onmetal-ironic-hardware-manager$ tox
py27 develop-inst-nodeps: /data/Users/jay/dev/onmetal-ironic-hardware-manager
py27 runtests: PYTHONHASHSEED='2803691587'
py27 runtests: commands[0] | python setup.py testr --slowest --testr-args=
running testr
running=OS_STDOUT_CAPTURE=1 OS_STDERR_CAPTURE=1 OS_TEST_TIMEOUT=60 ${PYTHON:-python} -m subunit.run discover -s onmetal_ironic_hardware_manager/tests/ -p "*.py"
Ran 16 (-3) tests in 0.032s (+0.001s)
PASSED (id=100)
Slowest Tests
Test id                                                                      Runtime (s)
---------------------------------------------------------------------------  -----------
manager.TestOnMetalVerifyPorts.test_verify_ports                             0.004
manager.TestOnMetalHardwareManager.test__list_lsi_devices                    0.002
manager.TestOnMetalHardwareManager.test_remove_bootloader                    0.002
manager.TestOnMetalVerifyPorts.test_verify_ports_mismatch                    0.002
manager.TestOnMetalVerifyPorts.test_verify_ports_unmatched                   0.002
manager.TestOnMetalHardwareManager.test_erase_block_device_lsi_error         0.001
manager.TestOnMetalVerifyPorts.test__get_tlv_malformed                       0.001
manager.TestOnMetalHardwareManager.test_erase_block_device_defer_to_generic  0.001
manager.TestOnMetalHardwareManager.test_erase_block_device_lsi_notfound      0.001
manager.TestOnMetalHardwareManager.test_erase_block_device_lsi_multiple      0.001
pep8 develop-inst-nodeps: /data/Users/jay/dev/onmetal-ironic-hardware-manager
pep8 runtests: PYTHONHASHSEED='2803691587'
pep8 runtests: commands[0] | flake8 onmetal_ironic_hardware_manager
git______________________________________________________________________________________ summary ______________________________________________________________________________________
  py27: commands succeeded
  pep8: commands succeeded
  congratulations :)
vagrant@vagrant-ubuntu-trusty-64:/data/Users/jay/dev/onmetal-ironic-hardware-manager$ git status
On branch jay/teeth-latest-proposed
nothing to commit, working directory clean
vagrant@vagrant-ubuntu-trusty-64:/data/Users/jay/dev/onmetal-ironic-hardware-manager$
```

**Comment by ClifHouck** [comment]
+1, also I don't seem to have write access to this repo.

**Comment by jimrollenhagen** [comment]
+1

**Pull request merged**
